### ISSUE TITLE
Update master branch

### ISSUE THREAD

**Issue by rsignell-usgs** [ooi-integration/cgsn-parsers#5]
The master branch hasn't been updated for months, so we were wondering if maybe the changes from the pypi branch be merged into master?
We would like to start contributing some code.

**Comment by cwingard** [comment]
Rich,

Yes. My plan was to merge the pypi branch into master within the next 
week. I've been working in pypi to pull in the suggested changes from 
Emilio, update some of the parsers and README language to better fit the 
newer system, and create an initial unittest framework. I just have the 
OPTAA (WET Labs AC-S) parser to work on, creating unittests. That's in 
progress right now.

Chris

**Comment by cwingard** [comment]
https://github.com/ooi-integration/cgsn-parsers/pull/7
